export default [
  {
    type: 'exchange',
    source_currency: 'NRFX',
    target_currency: 'BNB',
    source_amount: 0,
    target_amount: 0,
    timestamp: 1666282429,
  },
  {
    type: 'exchange',
    source_currency: 'RUB',
    target_currency: 'NRFX',
    source_amount: 0,
    target_amount: 0,
    timestamp: 1666687327,
  },
  {
    type: 'exchange',
    source_currency: 'BNB',
    target_currency: 'NRFX',
    source_amount: 0,
    target_amount: 0,
    timestamp: 1666687357,
  },
  {
    type: 'exchange',
    source_currency: 'RUB',
    target_currency: 'NRFX',
    source_amount: 0,
    target_amount: 0,
    timestamp: 1666687384,
  },
  {
    type: 'exchange',
    source_currency: 'BNB',
    target_currency: 'NRFX',
    source_amount: 0,
    target_amount: 0,
    timestamp: 1667485130,
  },
  {
    type: 'topup',
    source_currency: 'BNB',
    target_currency: 'BNB',
    source_amount: 0,
    target_amount: 0,
    timestamp: 1667485378,
  },
];
