// default
export const NAVIGATE = 'NAVIGATE';
export const SET_LANG = 'SET_LANG';
export const AUTH = 'AUTH';
export const STATIC = 'STATIC';
export const PROFILE = 'PROFILE';
export const LOGOUT = 'LOGOUT';
export const SET_USER_NAME = 'SET_USER_NAME';

export const PUSH_MODAL = 'PUSH_MODAL';
export const POP_MODAL = 'POP_MODAL';

//cabinet
export const WALLETS = 'WALLETS';
export const TRANSACTION_HISTORY = 'TRANSACTION_HISTORY';
export const WALLET_HISTORY = 'WALLET_HISTORY';
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_ADAPTIVE = 'SET_ADAPTIVE';
export const SET_TITLE = 'SET_TITLE';

// NotificationsScreen
export const NOTIFICATIONS_SET = 'NOTIFICATIONS_SET';

// InternalNotifications
export const INTERNAL_NOTIFICATION_LOAD = 'INTERNAL_NOTIFICATION_LOAD';
export const INTERNAL_NOTIFICATION_PUSH = 'INTERNAL_NOTIFICATION_PUSH';
export const INTERNAL_NOTIFICATION_DROP = 'INTERNAL_NOTIFICATION_DROP';

// Toasts
export const TOASTS_PUSH = 'TOASTS_PUSH';
export const TOASTS_DROP = 'TOASTS_DROP';
export const TOASTS_HIDE = 'TOASTS_HIDE';

// test
export const TEST = 'TEST';

// investments
export const INVESTMENTS_SET_LOADING_STATUS = 'INVESTMENTS_SET_LOADING_STATUS';
export const INVESTMENTS_SET = 'INVESTMENTS_SET';
export const INVESTMENTS_PROFITS_SET = 'INVESTMENTS_PROFITS_SET';
export const INVESTMENTS_PROFITS_APPEND = 'INVESTMENTS_PROFITS_APPEND';
export const INVESTMENTS_WITHDRAWALS_SET = 'INVESTMENTS_WITHDRAWALS_SET';
export const INVESTMENTS_WITHDRAWALS_APPEND = 'INVESTMENTS_WITHDRAWALS_APPEND';
export const INVESTMENTS_WITHDRAWALS_SET_LOADING_MORE_STATUS = 'INVESTMENTS_WITHDRAWALS_SET_LOADING_MORE_STATUS';

// settings
export const SETTINGS_SET_LOADING_STATUS = 'SETTINGS_SET_LOADING_STATUS';
export const SETTINGS_SET = 'SETTINGS_SET';
export const SETTINGS_USER_FIELD_SET = 'SETTINGS_USER_FIELD_SET';

// profile
export const PROFILE_SET_LOADING_STATUS = 'PROFILE_SET_LOADING_STATUS';
export const PROFILE_SET = 'PROFILE_SET_LOADING_STATUS';
export const PROFILE_DASHBOARD_SET = 'PROFILE_DASHBOARD_SET';

// wallets
export const WALLETS_SET_LOADING_STATUS = 'WALLETS_SET_LOADING_STATUS';
export const WALLETS_SET = 'WALLETS_SET';
export const WALLETS_TRANSACTIONS_SET = 'WALLETS_TRANSACTIONS_SET';
export const WALLETS_TRANSACTIONS_LOADING_MORE = 'WALLETS_TRANSACTIONS_LOADING_MORE';
export const WALLETS_TRANSACTIONS_APPEND = 'WALLETS_TRANSACTIONS_APPEND';

export const WALLETS_TRANFERS_SET = 'WALLETS_TRANFERS_SET';
export const WALLETS_TRANFERS_LOADING_MORE = 'WALLETS_TRANFERS_LOADING_MORE';
export const WALLETS_TRANFERS_APPEND = 'WALLETS_TRANFERS_APPEND';

// modalGroup
export const MODALGROUP_SET_ACTIVE_MODAL = 'MODALGROUP_SET_ACTIVE_MODAL';
export const MODALGROUP_ADD_CUSTOM_MODAL = 'MODALGROUP_ADD_CUSTOM_MODAL';
export const MODALGROUP_SET_STATE_BY_MODALPAGE = 'MODALGROUP_SET_STATE_BY_MODALPAGE';
