// default
export const NAVIGATE = "NAVIGATE";
export const SET_LANG = "SET_LANG";
export const SET_CURRENT_LANG = "SET_CURRENT_LANG";
export const AUTH = "AUTH";
export const PROFILE = "PROFILE";
export const PROFILE_PENDING = "PROFILE_PENDING";
export const LOGOUT = "LOGOUT";
export const SET_USER_NAME = "SET_USER_NAME";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const PUSH_MODAL = "PUSH_MODAL";
export const POP_MODAL = "POP_MODAL";

//cabinet
export const WALLETS = "WALLETS";
export const TRANSACTION_HISTORY = "TRANSACTION_HISTORY";
export const WALLET_HISTORY = "WALLET_HISTORY";
export const SET_CURRENCIES = "SET_CURRENCIES";
export const SET_ADAPTIVE = "SET_ADAPTIVE";
export const SET_TITLE = "SET_TITLE";
export const SET_THEME = "SET_THEME";
export const SET_CABINET = "SET_CABINET";
export const TRANSLATOR_TOGGLE = "TRANSLATOR_TOGGLE";
export const TRANSLATOR_SET_LANG_CODE = "TRANSLATOR_SET_LANG_CODE";
export const APIKEY_SET = "APIKEY_SET";
export const SECRETKEY_SET = "SECRETKEY_SET";
export const IS_SECRETKEY = "IS_SECRETKEY";
export const APIKEY_SET_LOADING_STATUS = "APIKEY_SET_LOADING_STATUS";
export const SETTINGS_CHECK_TRADING = "SETTINGS_CHECK_TRADING";
export const SETTINGS_CHECK_WITHDRAW = "SETTINGS_CHECK_WITHDRAW";
export const SETTINGS_IP_ACCESS = "SETTINGS_IP_ACCESS";
export const SETTINGS_IP_ADDRESS_FIELD_SET = "SETTINGS_IP_ADDRESS_FIELD_SET";
export const DELETE_IP_ADDRESS = "DELETE_IP_ADDRESS";
export const ADD_IP_ADDRESS = "ADD_IP_ADDRESS";
export const REGISTRATION_SET_VALUE = "REGISTRATION_SET_VALUE";
export const SAVE_TRANSLATOR = "SAVE_TRANSLATOR";

// NotificationsScreen
export const NOTIFICATIONS_SET = "NOTIFICATIONS_SET";
export const NOTIFICATIONS_DELETE = "NOTIFICATIONS_DELETE";
export const NOTIFICATIONS_RESTORE = "NOTIFICATIONS_RESTORE";

// InternalNotifications
export const INTERNAL_NOTIFICATION_LOAD = "INTERNAL_NOTIFICATION_LOAD";
export const INTERNAL_NOTIFICATION_PUSH = "INTERNAL_NOTIFICATION_PUSH";
export const INTERNAL_NOTIFICATION_DROP = "INTERNAL_NOTIFICATION_DROP";

// Toasts
export const TOASTS_PUSH = "TOASTS_PUSH";
export const TOASTS_DROP = "TOASTS_DROP";
export const TOASTS_HIDE = "TOASTS_HIDE";
export const TOASTS_SET_HIDE = "TOASTS_SET_HIDE";

// test
export const TEST = "TEST";

// investments
export const INVESTMENTS_SET_LOADING_STATUS = "INVESTMENTS_SET_LOADING_STATUS";
export const INVESTMENTS_SET = "INVESTMENTS_SET";
export const INVESTMENTS_PROFITS_SET = "INVESTMENTS_PROFITS_SET";
export const INVESTMENTS_PROFITS_APPEND = "INVESTMENTS_PROFITS_APPEND";
export const INVESTMENTS_WITHDRAWALS_SET = "INVESTMENTS_WITHDRAWALS_SET";
export const INVESTMENTS_WITHDRAWALS_APPEND = "INVESTMENTS_WITHDRAWALS_APPEND";
export const INVESTMENTS_WITHDRAWALS_SET_LOADING_MORE_STATUS =
  "INVESTMENTS_WITHDRAWALS_SET_LOADING_MORE_STATUS";
export const INVESTMENTS_OPEN_DEPOSIT_MODAL_PROPERTY_SET =
  "INVESTMENTS_OPEN_DEPOSIT_MODAL_PROPERTY_SET";
export const INVESTMENTS_OPEN_DEPOSIT_SUCCESS =
  "INVESTMENTS_OPEN_DEPOSIT_SUCCESS";

// settings
export const SETTINGS_SET_LOADING_STATUS = "SETTINGS_SET_LOADING_STATUS";
export const SETTINGS_SET = "SETTINGS_SET";
export const SETTINGS_USER_FIELD_SET = "SETTINGS_USER_FIELD_SET";

// profile
export const PROFILE_SET_LOADING_STATUS = "PROFILE_SET_LOADING_STATUS";
export const PROFILE_SET = "PROFILE_SET_LOADING_STATUS";
export const PROFILE_DASHBOARD_SET = "PROFILE_DASHBOARD_SET";
export const PROFILE_SET_GA_SUCCESS = "PROFILE_SET_GA_SUCCESS";
export const PROFILE_SET_SECRET_SUCCESS = "PROFILE_SET_SECRET_SUCCESS";

export const PROFILE_PARTNER_SET = "PROFILE_PARTNER_SET";
export const PROFILE_PARTNER_APPEND = "PROFILE_PARTNER_APPEND";
export const PROFILE_INVITE_LINK_UPDATE = "PROFILE_INVITE_LINK_UPDATE";
export const PROFILE_INVITE_LINK_ADD = "PROFILE_INVITE_LINK_ADD";
export const PROFILE_INVITE_LINK_DELETE = "PROFILE_INVITE_LINK_DELETE";
export const PROFILE_INVITE_LINK_RESTORE = "PROFILE_INVITE_LINK_RESTORE";
export const PROFILE_SET_VERIFICATION_STATUS =
  "PROFILE_SET_VERIFICATION_STATUS";

// wallets
export const WALLETS_SET_LOADING_STATUS = "WALLETS_SET_LOADING_STATUS";
export const WALLETS_SET = "WALLETS_SET";
export const WALLETS_TRANSACTIONS_SET = "WALLETS_TRANSACTIONS_SET";
export const WALLETS_TRANSACTIONS_LOADING_MORE =
  "WALLETS_TRANSACTIONS_LOADING_MORE";
export const WALLETS_TRANSACTIONS_APPEND = "WALLETS_TRANSACTIONS_APPEND";
export const WALLETS_NEW_TRANSACTION = "WALLETS_NEW_TRANSACTION";
export const WALLETS_NEW_TRANSFER = "WALLETS_NEW_TRANSFER";

export const WALLETS_TRANFERS_SET = "WALLETS_TRANFERS_SET";
export const WALLETS_TRANFERS_LOADING_MORE = "WALLETS_TRANFERS_LOADING_MORE";
export const WALLETS_TRANFERS_APPEND = "WALLETS_TRANFERS_APPEND";
export const WALLETS_GENERATE_SUCCESS = "WALLETS_GENERATE_SUCCESS";
export const WALLETS_SET_LIMITS = "WALLETS_SET_LIMITS";
export const WALLETS_SEND_COIN_MODAL_SET_VALUE =
  "WALLETS_SEND_COIN_MODAL_SET_VALUE";
export const WALLETS_SEND_COIN_MODAL_CLEAR = "WALLETS_SEND_COIN_MODAL_CLEAR";
export const WALLETS_WALLET_UPDATE = "WALLETS_WALLET_UPDATE";

// fiat wallets
export const FIAT_WALLETS_SET = "FIAT_WALLETS_SET";
export const FIAT_HISTORY_ADD_ITEMS = "FIAT_HISTORY_ADD_ITEMS";
export const FIAT_WALLETS_UPDATE = "FIAT_WALLETS_UPDATE";
export const FIAT_WALLETS_SET_RATE = "FIAT_WALLETS_SET_RATE";
export const FIAT_WALLETS_SET_LOADING_STATUS =
  "FIAT_WALLETS_SET_LOADING_STATUS";
export const FIAT_WALLETS_SET_MARKET_EXCHANGE =
  "FIAT_WALLETS_SET_MARKET_EXCHANGE";
export const FIAT_WALLETS_SET_MERCHANTS = "FIAT_WALLETS_SET_MERCHANTS";
export const FIAT_WALLETS_SET_WITHDRAWAL_BANK_LIST =
  "FIAT_WALLETS_SET_WITHDRAWAL_BANK_LIST";
export const FIAT_WALLETS_SET_REFILL_BANK_LIST =
  "FIAT_WALLETS_SET_REFILL_BANK_LIST";
export const FIAT_WALLETS_APPEND_TRANSACTION =
  "FIAT_WALLETS_APPEND_TRANSACTION";

// Exchange
export const EXCHANGE_SET = "EXCHANGE_SET";
export const EXCHANGE_SET_LOADING_STATUS = "EXCHANGE_SET_LOADING_STATUS";
export const EXCHANGE_REMOVE_ORDERS = "EXCHANGE_REMOVE_ORDERS";
export const EXCHANGE_ORDER_BOOK_UPDATE = "EXCHANGE_ORDER_BOOK_UPDATE";
export const EXCHANGE_ORDER_BOOK_INIT = "EXCHANGE_ORDER_BOOK_INIT";
export const EXCHANGE_ORDER_BOOK_SELECT_ORDER =
  "EXCHANGE_ORDER_BOOK_SELECT_ORDER";
export const EXCHANGE_TICKER_UPDATE = "EXCHANGE_TICKER_UPDATE";
export const EXCHANGE_SET_ORDER_STATUS = "EXCHANGE_SET_ORDER_STATUS";
export const EXCHANGE_ORDER_COMPLETED = "EXCHANGE_ORDER_COMPLETED";
export const EXCHANGE_ORDER_FAILED = "EXCHANGE_ORDER_FAILED";
export const EXCHANGE_SET_ORDER_PENDING = "EXCHANGE_SET_ORDER_PENDING";
export const EXCHANGE_TRADING_FORM_SET_TYPE = "EXCHANGE_TRADING_FORM_SET_TYPE";
export const EXCHANGE_TRADING_FORM_SET_PROPERTIES =
  "EXCHANGE_TRADING_FORM_SET_PROPERTIES";
export const EXCHANGE_ADD_OPEN_ORDER = "EXCHANGE_ADD_OPEN_ORDER";
export const EXCHANGE_ADD_ORDER_HISTORY = "EXCHANGE_ADD_ORDER_HISTORY";
export const EXCHANGE_ORDER_BOOK_REMOVE_ORDER =
  "EXCHANGE_ORDER_BOOK_REMOVE_ORDER";
export const EXCHANGE_ADD_TRADES = "EXCHANGE_ADD_TRADES";
export const EXCHANGE_UPDATE_BALANCE = "EXCHANGE_UPDATE_BALANCE";
export const EXCHANGE_CHANGE_TIME_FRAME = "EXCHANGE_CHANGE_TIME_FRAME";
export const EXCHANGE_SET_MARKETS = "EXCHANGE_SET_MARKETS";
export const EXCHANGE_SET_FULLSCREEN = "EXCHANGE_SET_FULLSCREEN";

// Admin
export const ADMIN_INIT = "ADMIN_INIT";
export const ADMIN_VALUE_CHANGE = "ADMIN_INPUT_CHANGE";

// Admin
export const LANGS_SET_TYPE = "LANGS_SET_TYPE";
export const LANGS_SET_LANG = "LANGS_SET_LANG";
export const LANGS_SET_STATUS = "LANGS_SET_STATUS";
export const LANGS_KEY_DELETE = "LANGS_KEY_DELETE";
export const LANGS_SET_KEYS = "LANGS_SET_KEYS";
export const LANGS_SET_KEY_NEW_VALUE = "LANGS_SET_KEY_NEW_VALUE";
export const LANGS_SET_FILTER = "LANGS_SET_FILTER";
export const LANGS_ADD_NEW_KEY = "LANGS_ADD_NEW_KEY";
export const LANGS_SAVE = "LANGS_SAVE";

// Trader
export const TRADER_INIT = "BOTS_INIT";
export const TRADER_BOT_INIT = "TRADER_BOT_INIT";
export const TRADER_BOT_UPDATE = "TRADER_BOT_UPDATEZ";
export const TRADER_OPTIONS_UPDATE = "TRADER_OPTIONS_UPDATE";
export const TRADER_BOT_SET_PROPERTY = "TRADER_BOT_SET_PROPERTY";
export const TRADER_BOT_SET_INDICATOR_PROPERTY =
  "TRADER_BOT_SET_INDICATOR_PROPERTY";
export const TRADER_SET_LOADING_STATUS = "TRADER_SET_LOADING_STATUS";

// Documentation
export const DOCUMENTATION_SET_STATUS = "DOCUMENTATION_SET_STATUS";
export const DOCUMENTATION_METHOD = "DOCUMENTATION_METHOD";
export const DOCUMENTATION_INIT = "DOCUMENTATION_INIT";
export const DOCUMENTATION_SET_PAGE = "DOCUMENTATION_SET_PAGE";
export const DOCUMENTATION_UPDATE_PAGE_CONTENT =
  "DOCUMENTATION_UPDATE_PAGE_CONTENT";
export const DOCUMENTATION_UPDATE_METHOD = "DOCUMENTATION_UPDATE_METHOD";
export const DOCUMENTATION_SET_EDIT_MODE = "DOCUMENTATION_SET_EDIT_MODE";
export const DOCUMENTATION_UPDATE_METHOD_PARAM_DESC =
  "DOCUMENTATION_UPDATE_METHOD_PARAM_DESC";

export const LANDING_SET_MARKETS = "LANDING_SET_MARKETS";
