// Dapp
export const DAPP_SET_SWAP = 'DAPP_SET_SWAP';
export const DAPP_SET_WITHDRAW = 'DAPP_SET_WITHDRAW';
export const DAPP_SET_WALLET_TOKENS = 'DAPP_SET_WALLET_TOKENS';

// Transactions
export const DAPP_SET_TRANSACTION_ITEMS = 'DAPP_SET_TRANSACTION_ITEMS';
export const DAPP_SET_TRANSACTIONS_STATUS = 'DAPP_SET_TRANSACTIONS_STATUS';
export const DAPP_SORT_TRANSACTIONS = 'DAPP_SORT_TRANSACTIONS';