// Dapp
export const DAPP_SET_SWAP = 'DAPP_SET_SWAP';
export const DAPP_SET_WITHDRAW = 'DAPP_SET_WITHDRAW';
export const DAPP_SET_WALLET_TOKENS = 'DAPP_SET_WALLET_TOKENS';
export const DAPP_SET_INVOICE = 'DAPP_SET_INVOICE';

// Transactions
export const DAPP_SET_TRANSACTION_ITEMS = 'DAPP_SET_TRANSACTION_ITEMS';
export const DAPP_SET_TRANSACTIONS_STATUS = 'DAPP_SET_TRANSACTIONS_STATUS';
export const DAPP_SORT_TRANSACTIONS = 'DAPP_SORT_TRANSACTIONS';

// Exchange
export const DAPP_SET_EXCHANGE_AMOUNT = 'DAPP_SET_EXCHANGE_AMOUNT';
export const DAPP_SET_EXCHANGE_TOKEN = 'DAPP_SET_EXCHANGE_TOKEN';
export const DAPP_SET_EXCHANGE_FOCUS = 'DAPP_SET_EXCHANGE_FOCUS';

// P2P
export const DAPP_SET_P2P_MODE = 'DAPP_SET_P2P_MODE';
export const DAPP_SET_P2P_PAYMENT = 'DAPP_SET_P2P_PAYMENT';
