export const COMPONENT_MODALGROUP = 'COMPONENT_MODALGROUP';
export const COMPONENT_PROFILE_SIDEBAR = 'COMPONENT_PROFILE_SIDEBAR';

// CABINET CLASSES CONTAINERS
export const CABINET_START_PFOFILE_SCREEN = 'CABINET_START_PFOFILE_SCREEN';
export const CABINET_PFOFILE_SCREEN = 'CABINET_PFOFILE_SCREEN';
export const CABINET_WALLET_SCREEN = 'CABINET_WALLET_SCREEN';
export const CABINET_INVESTMENTS_SCREEN = 'CABINET_INVESTMENTS_SCREEN';
export const CABINET_SETTINGS_SCREEN = 'CABINET_SETTINGS_SCREEN';

// CABINET COMPONENTS CLASSES MODALS
export const SEND_COINS_MODAL = 'SEND_COINS_MODAL';