export const COMPONENT_MODALGROUP = 'COMPONENT_MODALGROUP';
export const COMPONENT_PROFILE_SIDEBAR = 'COMPONENT_PROFILE_SIDEBAR';
export const COMPONENT_CABINET_HEADER = 'COMPONENT_CABINET_HEADER';
export const COMPONENT_CABINET_WRAPPER = 'COMPONENT_CABINET_WRAPPER';
export const COMPONENT_TOASTS = 'COMPONENT_TOASTS';
export const COMPONENT_FOOTER = 'COMPONENT_FOOTER';

// CABINET CLASSES CONTAINERS
export const CABINET_START_PFOFILE_SCREEN = 'CABINET_START_PFOFILE_SCREEN';
export const CABINET_PFOFILE_SCREEN = 'CABINET_PFOFILE_SCREEN';
export const CABINET_WALLET_SCREEN = 'CABINET_WALLET_SCREEN';
export const CABINET_INVESTMENTS_SCREEN = 'CABINET_INVESTMENTS_SCREEN';
export const CABINET_SETTINGS_SCREEN = 'CABINET_SETTINGS_SCREEN';
export const CABINET_MENU_SCREEN = 'CABINET_MENU_SCREEN';
export const CABINET_NOTIFICATIONS_SCREEN = 'CABINET_NOTIFICATIONS_SCREEN';
export const CABINET_REGISTER = 'CABINET_REGISTER';
export const CABINET_RESET_PASSWORD = 'CABINET_RESET_PASSWORD';
export const CABINET_EXCHANGE_SCREEN = 'CABINET_EXCHANGE_SCREEN';

// CABINET COMPONENTS CLASSES MODALS
export const SEND_COINS_MODAL = 'SEND_COINS_MODAL';
export const CHANGE_SECRET_KEY_MODAL = 'CHANGE_SECRET_KEY_MODAL';
export const GOOGLE_CODE_MODAL = 'GOOGLE_CODE_MODAL';
export const SEND_COINS_CONFIRM_MODAL = 'SEND_COINS_CONFIRM_MODAL';
export const WITHDRAWAL_COINS_MODAL = 'WITHDRAWAL_COINS_MODAL';
export const OPEN_DEPOSIT_MODAL = 'OPEN_DEPOSIT_MODAL';
export const CONFIRM_SMS_MODAL = 'CONFIRM_SMS_MODAL';
export const CHANGE_EMAIL_MODAL = 'CHANGE_EMAIL_MODAL';
export const CHANGE_PHONE_NUMBER_MODAL = 'CHANGE_PHONE_NUMBER_MODAL';
export const EXCHANGE_BALANCE_MODAL = 'EXCHANGE_BALANCE_MODAL';
