export default {
  "nrfx": {
    "abbr": "nrfx",
    "name": "Narfex Token",
    "icon": "https://static.narfex.com/img/currencies/nrfx.svg",
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#FFA041",
    "gradient": ["#FABE4C", "#FA9751"],
    "is_available": true,
    "can_exchange": true,
    "to_usd": 0.5,
    "commission": 0.01,
  },
  "btc": {
    "abbr": "btc",
    "name": "Bitcoin",
    "icon": "https://static.narfex.com/img/currencies/bitcoin.svg",
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#ff9900",
    "gradient": ["#ff9900", "#ff9900"],
    "is_available": true,
    "can_exchange": false,
    "to_usd": 9589.923
  },
  "eth": {
    "abbr": "eth",
    "name": "Ethereum",
    "icon": "https://static.narfex.com/img/currencies/ethereum.svg",
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#908EE8",
    "gradient": ["#896ADF", "#98B1F1"],
    "is_available": true,
    "can_exchange": false,
    "to_usd": 251.54745000000003
  },
  "ltc": {
    "abbr": "ltc",
    "name": "Litecoin",
    "icon": "https://static.narfex.com/img/currencies/litecoin.svg",
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#75BBE7",
    "gradient": ["#619ABE", "#7AC4F2"],
    "is_available": true,
    "can_exchange": false,
    "to_usd": 46.47685
  },
  "xrp": {
    "abbr": "xrp",
    "name": "Ripple",
    "icon": "https://static.narfex.com/img/currencies/ripple.svg",
    "is_exists": false,
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#3697E1",
    "gradient": ["#3FBEFC", "#2C74C7"],
    "can_exchange": false,
    "to_usd": 0.203
  },
  "bchabc": {
    "abbr": "bchabc",
    "name": "Bitcoin Cash ABC",
    "icon": "https://static.narfex.com/img/currencies/bitcoincash.svg",
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#F8AC4D",
    "gradient": ["#F8A15D", "#F7B73B"],
    "can_exchange": false,
    "to_usd": 0
  },
  "usdt": {
    "abbr": "usdt",
    "name": "Tether",
    "icon": "https://static.narfex.com/img/currencies/tether.svg",
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#5AA58C",
    "gradient": ["#5AA58C", "#5AA58C"],
    "can_exchange": true,
    "to_usd": 0,
    "commission": 0.12,
  },
  "usd": {
    "abbr": "usd",
    "name": "U.S. Dollar",
    "icon": "https://static.narfex.com/img/currencies/dollar.svg",
    "type": "fiat",
    "maximum_fraction_digits": 2,
    "color": "#6CC592",
    "gradient": ["#62B27D", "#77D9A8"],
    "can_exchange": false,
    "to_usd": 1
  },
  "eur": {
    "abbr": "eur",
    "name": "Euro",
    "icon": "https://static.narfex.com/img/currencies/euro.svg",
    "type": "fiat",
    "maximum_fraction_digits": 2,
    "color": "#6CC592",
    "gradient": ["#62B27D", "#77D9A8"],
    "can_exchange": false,
    "to_usd": 0.8814102157024618
  },
  "rub": {
    "abbr": "rub",
    "name": "Rubles",
    "icon": "https://static.narfex.com/img/currencies/rubles.svg",
    "type": "fiat",
    "maximum_fraction_digits": 2,
    "color": "#6CC592",
    "gradient": ["#62B27D", "#77D9A8"],
    "can_exchange": true,
    "to_usd": 70.98314917127071
  },
  "idr": {
    "abbr": "idr",
    "name": "Indonesian Rupiah",
    "icon": "https://static.narfex.com/img/currencies/indonesian-rupiah.svg",
    "type": "fiat",
    "maximum_fraction_digits": 2,
    "color": "#6CC592",
    "gradient": ["#62B27D", "#77D9A8"],
    "can_exchange": false,
    "to_usd": 14422.522032768144
  },
  "cny": {
    "abbr": "cny",
    "name": "Chinese Yuan",
    "icon": "https://static.narfex.com/img/currencies/yuan-cny.svg",
    "type": "fiat",
    "maximum_fraction_digits": 2,
    "color": "#6CC592",
    "gradient": ["#62B27D", "#77D9A8"],
    "can_exchange": false,
    "to_usd": 6.986069304206091
  },
  "gbp": {
    "abbr": "gbp",
    "name": "British Pound",
    "icon": "https://static.narfex.com/img/currencies/gbp-pound.svg",
    "type": "fiat",
    "maximum_fraction_digits": 2,
    "color": "#6CC592",
    "gradient": ["#62B27D", "#77D9A8"],
    "can_exchange": false,
    "to_usd": 0.7929764399568171
  },
  "bnb": {
    "abbr": "bnb",
    "name": "Binance Coin",
    "icon": "https://static.narfex.com/img/currencies/bnb1.svg",
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#FFA041",
    "gradient": ["#FABE4C", "#FA9751"],
    "is_available": true,
    "can_exchange": true,
    "to_usd": 0.5,
    "commission": 0.03,
  },
  "busd": {
    "abbr": "busd",
    "name": "Binance USD",
    "icon": "https://static.narfex.com/img/currencies/busd.svg",
    "type": "crypto",
    "maximum_fraction_digits": 8,
    "color": "#FFA041",
    "gradient": ["#FABE4C", "#FA9751"],
    "can_exchange": true,
    "to_usd": 0,
    "commission": 0.12,
  },
}
